### ISSUE TITLE
[Enhancement] subtext on homepage seems off

### ISSUE THREAD

**Issue by swaleha6** [info442-aut21/g-team#45]
[Enhancement] subtext on homepage seems off, the way that "Connecting" is on it's own line makes the sentence feel choppy

**Comment by njkpark** [comment]
"Connecting" is on its own line most likely due to the responsiveness of the page. In a full screen browser, the subtext is not misaligned or the words are not on their own line. However, when making the screen smaller, it's bound to alter the text layout. This is not a big enough of an enhancement to work on.
